# Arrays com numpy

In [1]:
import numpy as np

In [2]:
import sys

In [3]:
sys.version

'3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'

In [4]:
np.__version__

'1.11.1'

In [5]:
array1 = np.arange(0,15)

In [6]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
#Valor maximo
array1.max()

14

In [8]:
#Valor minimo
array1.min()

0

In [10]:
#Valor medio
array1.mean()

7.0

In [11]:
#Desvio padrao
array1.std()

4.3204937989385739

In [16]:
#Utilizando list comprehension
[x * x for x in array1 if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

In [20]:
#Utilizando expressoes lambda e map
list(map(lambda x:x*x,filter(lambda x:x%2==0,array1)))

[0, 4, 16, 36, 64, 100, 144, 196]

# Avaliando a performance

In [22]:
%timeit [x * x for x in array1 if x % 2 == 0]

100000 loops, best of 3: 7.22 µs per loop


In [23]:
%timeit array1[array1 % 2 == 0]

The slowest run took 48.39 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.89 µs per loop


# Concatenando arrays

In [24]:
array2 = np.ones(5)

In [25]:
array2

array([ 1.,  1.,  1.,  1.,  1.])

In [26]:
array3 = np.arange(0,15)

In [27]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [30]:
array4 = np.concatenate((array2,array3))

In [31]:
array4

array([  1.,   1.,   1.,   1.,   1.,   0.,   1.,   2.,   3.,   4.,   5.,
         6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.])

# Join de arrays

In [33]:
array5 = np.zeros((3,3))

In [34]:
array5

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [35]:
array6 = np.ones((3,3))

In [36]:
array6

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [38]:
np.hstack((array5,array6))

array([[ 0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  1.]])

In [39]:
np.vstack((array5,array6))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [40]:
np.column_stack((array5,array6))

array([[ 0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  1.],
       [ 0.,  0.,  0.,  1.,  1.,  1.]])

In [42]:
np.row_stack((array5,array6))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

# Split de arrays


In [51]:
array7 = np.arange(0,16).reshape((4,4))

In [52]:
array7

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [53]:
[array8,array9] = np.hsplit(array7,2)

In [54]:
array8

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [55]:
array9

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [56]:
[array8,array9] = np.vsplit(array7,2)

In [57]:
array8

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [58]:
array9

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Gravando e carregando dados

In [59]:
dados = array7

In [60]:
np.save("dadosGravados",dados)

In [61]:
np.load("dadosGravados.npy")

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])