# Trabalhando com matrizes

In [4]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]


'1.11.1'

# Criando matrizes

In [7]:
mat1 = np.matrix("1,2,3;4,5,6")

In [8]:
mat1

matrix([[1, 2, 3],
        [4, 5, 6]])

In [9]:
type(mat1)

numpy.matrixlib.defmatrix.matrix

In [10]:
mat2 = np.matrix(([1,2,3],[4,5,6]))

In [11]:
type(mat2)

numpy.matrixlib.defmatrix.matrix

In [13]:
mat2

matrix([[1, 2, 3],
        [4, 5, 6]])

In [15]:
mat3 = np.matrix([[0,10,0,0,0],[0,0,20,0,0],[0,0,30,0,0],[0,0,0,40,0],[0,0,0,0,50]])

In [16]:
mat3


matrix([[ 0, 10,  0,  0,  0],
        [ 0,  0, 20,  0,  0],
        [ 0,  0, 30,  0,  0],
        [ 0,  0,  0, 40,  0],
        [ 0,  0,  0,  0, 50]])

In [24]:
mat3[4,4]

50

# Matrizes esparsas

In [25]:
import scipy.sparse

In [28]:
linha = np.array([0,1,2,3])
coluna= np.array([1,2,3,4])
valores = np.array([10,20,30,40])

In [32]:
mat4 = scipy.sparse.coo_matrix((valores,(linha,coluna)))

In [33]:
mat4

<4x5 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in COOrdinate format>

In [34]:
print(mat4)

  (0, 1)	10
  (1, 2)	20
  (2, 3)	30
  (3, 4)	40


In [36]:
print(mat4.todense())

[[ 0 10  0  0  0]
 [ 0  0 20  0  0]
 [ 0  0  0 30  0]
 [ 0  0  0  0 40]]


# Operações com arrays e matrizes

In [39]:
a = np.array([[1,2],[3,4]])

In [40]:
a

array([[1, 2],
       [3, 4]])

In [43]:
mat_a = np.mat(a)

In [44]:
mat_a

matrix([[1, 2],
        [3, 4]])

In [47]:
# A multiplicação de matrizes ocorre de forma diferente
# é a representacao matematica de matrizes
# na multiplicacao, linha deve multiplicar coluna
print(mat_a*mat_a)

[[ 7 10]
 [15 22]]


In [48]:
a

array([[1, 2],
       [3, 4]])

In [51]:
a = np.asmatrix(a)

In [52]:
a

matrix([[1, 2],
        [3, 4]])

In [53]:
a = np.asarray(a)

In [54]:
a


array([[1, 2],
       [3, 4]])