In [1]:
import numpy as np

In [3]:
array1 = np.random.randint(0,50,20)

In [4]:
array1


array([40,  2, 29, 33, 26,  1, 19, 33,  1, 26, 31, 11, 11, 46, 38, 38,  6,
       30, 39, 41])

In [5]:
#Nova funcao
def calc_num(num):
    if num < 10:
        return num ** 3
    else:
        return num ** 2

In [9]:
calc_num(10)

100

In [11]:
# Não é possivel aplicar uma funcao a todo um vetor numpy
# E necessario vetorizar a funcao
v_calc_num = np.vectorize(calc_num)

In [12]:
type(v_calc_num)

numpy.lib.function_base.vectorize

In [13]:
v_calc_num(array1)

array([1600,    8,  841, 1089,  676,    1,  361, 1089,    1,  676,  961,
        121,  121, 2116, 1444, 1444,  216,  900, 1521, 1681])

# Com funcao Map

In [15]:
# Posso obter o mesmo resultado utilizando a funcao map
list(map(calc_num,array1))

[1600,
 8,
 841,
 1089,
 676,
 1,
 361,
 1089,
 1,
 676,
 961,
 121,
 121,
 2116,
 1444,
 1444,
 216,
 900,
 1521,
 1681]

# Com List Comprehension

In [16]:
[calc_num(x) for x in array1]

[1600,
 8,
 841,
 1089,
 676,
 1,
 361,
 1089,
 1,
 676,
 961,
 121,
 121,
 2116,
 1444,
 1444,
 216,
 900,
 1521,
 1681]

# Desempenho

In [17]:
%timeit [calc_num(x) for x in array1]
%timeit list(map(calc_num,array1))
%timeit v_calc_num(array1)

The slowest run took 8.05 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 10.5 µs per loop
100000 loops, best of 3: 10.5 µs per loop
The slowest run took 11.17 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 3: 29.4 µs per loop


# Com um array um pouco maior

In [18]:
array2 = np.random.randint(0,50,20000)

In [19]:
array2

array([21,  6,  8, ..., 16, 35, 43])

In [21]:
%timeit [calc_num(x) for x in array2]
%timeit list(map(calc_num,array2))
%timeit v_calc_num(array2)

100 loops, best of 3: 9.09 ms per loop
100 loops, best of 3: 9.12 ms per loop
100 loops, best of 3: 10.9 ms per loop
